# Generated by Django 3.2.9 on 2021-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
