# Generated by Django 3.2.9 on 2021-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='cldr_name',
            field=models.CharField(default='smile', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
