# Generated by Django 3.2.9 on 2021-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_alter_thread_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
    ]
