# Generated by Django 3.2.9 on 2021-12-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_alter_emoji_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='icon_url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
