# Generated by Django 3.2.9 on 2021-11-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_auto_20211117_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thread.emoji'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='reply_time',
            field=models.DateTimeField(),
        ),
    ]
