# Generated by Django 3.2.9 on 2021-11-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_auto_20211117_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thread.emoji'),
        ),
    ]
