# Generated by Django 3.2.9 on 2021-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_alter_emoji_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='forum_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='forumuser',
            unique_together={('forum_id', 'site')},
        ),
    ]
