# Generated by Django 3.2.9 on 2021-11-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_alter_comment_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Thread',
            new_name='thread',
        ),
    ]
