# Generated by Django 3.2.9 on 2021-11-17 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(choices=[('WE', 'Weekendhk'), ('OR', 'OpenRice'), ('YH', 'Yahoo')], max_length=2)),
                ('content', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.author')),
            ],
        ),
    ]
