# Generated by Django 3.2.9 on 2021-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('site', 'WE')), fields=['site'], name='site_index'),
        ),
    ]
