# Generated by Django 3.2.9 on 2021-11-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_site_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='site_index',
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('site', 'WE')), fields=['site'], name='site_index_WE'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('site', 'OR')), fields=['site'], name='site_index_OR'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(condition=models.Q(('site', 'YH')), fields=['site'], name='site_index_YH'),
        ),
    ]
